### PR TITLE
User API

### PR DESCRIPTION
**Pull request by mirzahilmi**
**Status**: On Progress

TODO:
- [x] Create User: `POST /api/v1/users`
- [x] Create Bulk User: `POST /api/v1/users` -> support for csv file upload
- [x] Get User: `GET /api/v1/users/{id}`
- [x] Delete User: `DELETE /api/v1/users/{id}`
- [x] Implement Repository Layer
- [x] Implement Usecase Layer
- [x] Implement HTTP Layer
- [x] Store Repository Unit Test
- [x] Integration Testing (k6)
- [x] Seeder for Testing

tag: @Daffadon

### CODE REVIEW

**Comment by mirzahilmi** [comment]
I think its better to split branch for the deployment prep, wdyt @Daffadon

**Comment by Daffadon** [comment]
please provide staging branch for the deployment. We need to know if newer version is running properly and not breaking the production. thank you @mirzahilmi. please proceed with your idea

**Comment by mirzahilmi** [comment]
> please provide staging branch for the deployment. We need to know if newer version is running properly and not breaking the production. thank you @mirzahilmi. please proceed with your idea

on it, ill make a simple cd pipeline to stage changes from dev branch in this repo. I'll notify the staging server address after its finished.

**Comment by mirzahilmi** [comment]
Oops, wrong target 🫠, im going to revert master branch and reopen PR targetting dev branch

**Pull request merged**
